.Net & Framework/13 Day/MVCSession/MVCSession/Models/ErrorViewModel.cs
namespace MVCSession.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.Net & Framework/13 Day/MVCSession/MVCSession/Models/UserLogin.cs
using System.ComponentModel.DataAnnotations;

namespace MVCSession.Models
{
    public class UserLogin
    {
        public string Email { get; set; }
        public int Age { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
      
        public bool Remember { get; set; }

    }
}

.Net & Framework/13 Day/MVCSession/MVCSession/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCSession.Models;
using System.Diagnostics;

namespace MVCSession.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {

                return View();
            }
            return RedirectToAction("Index");
              
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

.Net & Framework/13 Day/MVCSession/MVCSession/Controllers/SessionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using MVCSession.Models;

namespace MVCSession.Controllers
{
    public class SessionController : Controller
    {
        const string SessionEmail= "_Name";
        const string SessionAge = "_Age";
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString(SessionEmail) != null)
            {
                ViewBag.Email = HttpContext.Session.GetString(SessionEmail);
                ViewBag.Age = HttpContext.Session.GetInt32(SessionAge);
                ViewBag.Sid = HttpContext.Session.Id;
                ViewData["Message"] = "Asp.Net Core !!!.";
                return View();

            }
            return RedirectToAction("Create");
        }
        // GET: UserLoginController/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: UserLoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserLogin Userdata)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (Userdata.Email == "vita@cdac.in")
                    {
                        HttpContext.Session.SetString(SessionEmail, Userdata.Email);
                        HttpContext.Session.SetInt32(SessionAge, Userdata.Age);
                        return RedirectToAction("Privacy", "Home");
                    }
                    else {
                        ModelState.AddModelError("Email", "Not a Valid email");
                        return View(Userdata);
                    }
                }
                else { return View(); }                
            }
            catch
            {
                return View(Userdata);
            }
        }
        [HttpPost]
        public ActionResult Delete()
        {
            HttpContext.Session.Remove(SessionEmail);

            return RedirectToAction("Create");
        }
        
        public ActionResult DeleteData()
        {
            HttpContext.
                Session.Remove(SessionEmail);

            return RedirectToAction(nameof(Create));
        }

    }
}

.Net & Framework/13 Day/MVCSession/MVCSession/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.Net & Framework/13 Day/MVCSession/MVCSession/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCSession</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCSession.styles.css" asp-append-version="true" />
</head>
<body>
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCSession</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(HttpContextAccessor?.HttpContext?.Session.GetString("_Name") == null)
                        {
                              <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Create">Login</a>
                            </li>
                        }
                        else     {
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="DeleteData">Logout</a>
                        </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCSession - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>