.Net & Framework/13 Day/MVCfileup/MVCfileup/Models/Employee.cs
namespace MVCfileup.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? MyHobies { get; set; }
    }


}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Models/ErrorViewModel.cs
namespace MVCfileup.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Models/FileModel.cs
namespace MVCfileup.Models
{
    public class FileModel
    {
        public string FileName { get; set; }
        public IFormFile fromfile { get; set; }
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/ViewModels/EmployeeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCfileup.Models;

namespace MVCfileup.ViewModels
{
    public class EmployeeViewModel
    {
       public Employee emp {  get; set; }
        public IEnumerable<string> selHobbies { get; set; }
        public List<SelectListItem> listHobies { get; } = new List<SelectListItem>()
        {
            new SelectListItem { Value = "Dance", Text = "Dance" },
            new SelectListItem { Value = "Music", Text = "Music" },
            new SelectListItem { Value = "Sports", Text = "Sports"    }


        };
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/ViewModels/ProgrammingLanguages.cs
namespace MVCfileup.ViewModels
{
    public class ProgrammingLanguagesViewModel
    {
        public List<LanguageOption> LanguageOptions { get; set; }
    }
    public class LanguageOption
    {
        public bool IsSelected { get; set; }
        public string LanguageName { get; set; }
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Controllers/FileuploadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace MVCfileup.Controllers
{
    public class FileuploadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SingleFileUpload(IFormFile SingleFile)
        {
            if (ModelState.IsValid)
            {
                if (SingleFile != null && SingleFile.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", SingleFile.FileName);
                    //Using Buffering
                  /*  using (var stream = System.IO.File.Create(filePath))
                    {
                        // The file is saved in a buffer before being processed
                         SingleFile.CopyTo(stream);
                    }*/
                    //Using Streaming
                    using (var stream = new FileStream(filePath, FileMode.Create, FileAccess.Write))
                    {
                       await SingleFile.CopyToAsync(stream);
                    }
                    // Process the file here (e.g., save to the database, storage, etc.)
                    return View("UploadSuccess");
                }
            }
            return View("Index");
        }
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCfileup.Models;
using System.Diagnostics;

namespace MVCfileup.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public class FileUploadController : Controller
        {
            public IActionResult Index()
            {
                return View();
            }
        }
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using MVCfileup.ViewModels;

namespace MVCfileup.Controllers
{
   
        public class LanguageController : Controller
        {
            public IActionResult SelectLanguages()
            {
                var model = new ProgrammingLanguagesViewModel   {

                    LanguageOptions = new List<LanguageOption>
                {
                    new LanguageOption { IsSelected = false, LanguageName = "C#" },
                    new LanguageOption { IsSelected = false, LanguageName = "ASP.NET Core" },
                    new LanguageOption { IsSelected = false, LanguageName = "Python" },
                    new LanguageOption { IsSelected = false, LanguageName = "Java" },
                    new LanguageOption { IsSelected = false, LanguageName = "Ruby" },
                    new LanguageOption { IsSelected = false, LanguageName = "C++" }
                }
                };
                return View(model);
            }
            [HttpPost]
            public IActionResult SubmitLanguages(ProgrammingLanguagesViewModel model)
            {            // Filter the selected languages
                var selectedLanguages = model.LanguageOptions
                    .Where(option => option.IsSelected)
                    .Select(option => option.LanguageName)
                    .ToList();
                // Do something with the selected languages (e.g., display them on a results page)
               // ViewBag.SelectedLanguages = selectedLanguages;
                return View(selectedLanguages);
            }

        }
    }

.Net & Framework/13 Day/MVCfileup/MVCfileup/Controllers/SelctmultiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCfileup.Models;
using MVCfileup.ViewModels;
using System.Reflection;

namespace MVCfileup.Controllers
{
    public class SelctmultiController : Controller
    {
        public IActionResult Create()
        {            
            EmployeeViewModel empv = new EmployeeViewModel();                   

            return View(empv);
        }
        [HttpPost]
        public ActionResult Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
           {
                string hobbiesSelected = "";
                foreach (string s in model.selHobbies)
                {
                    hobbiesSelected = hobbiesSelected + " " + s;
                }
      
                Employee e1=new Employee() 
                { Id=model.emp.Id,
                  Name=model.emp.Name,
                  MyHobies= hobbiesSelected
                };
                return RedirectToAction(nameof(IndexSuccess),e1);
           }

            return View(model);
        }
        public ActionResult IndexSuccess(Employee model)
        {
            //ViewData["Message"] = message;
            return View(model);
        }
    }
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.Net & Framework/13 Day/MVCfileup/MVCfileup/Views/Language/SelectLanguages.cshtml
@model MVCfileup.ViewModels.ProgrammingLanguagesViewModel
@{
    ViewData["Title"] = "SelectLanguages";
}
<h1>SelectLanguages</h1>
<h4>ProgrammingLanguagesViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SubmitLanguages" asp-controller="Language" method="post">
            @*
            This begins an HTML form element.
            The 'asp-action' attribute specifies that the form will submit data to the 'SubmitLanguages' action method in the 'Language' controller.
            The 'method="post"' specifies that the form will use the HTTP POST method to send data to the server.
            *@
            @for (int i = 0; i < Model.LanguageOptions.Count; i++)
            {
                // A for-loop that iterates over the 'LanguageOptions' list in the bound model (ProgrammingLanguagesViewModel).
                // 'LanguageOptions' is a collection of LanguageOption objects, each representing a programming language.
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.LanguageOptions[i].IsSelected)
                    @* This generates a checkbox input element for the 'IsSelected' property of the current LanguageOption object.
                CheckBoxFor is a strongly-typed helper method that binds the checkbox to the 'IsSelected' property.
                When the form is submitted, the checkbox state (checked or unchecked) will be sent as part of the form data.*@

                    <label>@Model.LanguageOptions[i].LanguageName</label>
                    @* This creates an HTML label element next to the checkbox.
                It displays the name of the programming language by accessing the 'LanguageName' property of the current LanguageOption object. *@

                    @Html.HiddenFor(m => m.LanguageOptions[i].LanguageName)
                    @*
                This generates a hidden input element for the 'LanguageName' property of the current LanguageOption object.
                HiddenFor is a strongly-typed helper method that binds the hidden input to the 'LanguageName' property.
                This ensures that the programming language's name is also submitted with the form data, even though it is not visible on the form.
                *@
                </div>
            }

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Views/Language/SubmitLanguages.cshtml
@model List<string>
@{
    ViewData["Title"] = "SelectedLanguages";
}
<h2>Selected Programming Languages</h2>
@if (Model.Count == 0)
{
    <p>No languages selected.</p>
}
else
{
    <ul>
        @foreach (var language in Model)
        {
            <li>@language</li>
        }
    </ul>
}

.Net & Framework/13 Day/MVCfileup/MVCfileup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCfileup</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCfileup.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCfileup</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCfileup - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>